---
title: "Welcome to Tidybiology"
author:
- name: Matthew Hirschey
  affiliation: Duke University
  affiliation_url: https://duke.edu
- name: Akshay Bareja
date: "`r Sys.Date()`"
description: |
  R and data science for biologists
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Links to Class presentations

+ [Introduction](class_one/)
+ [Data Wrangling with Dplyr](class_two/)
+ [Plotting with Ggplot2](class_three/)
+ [Stringr and Joins](class_four/)
+ [R Markdown](class_five/)
+ [CCT Staci Reynolds](cct_staci/)
+ [Xaringan Dplyr](xaringan_dplyr/index.html)
+ [Xaringan Joins](xaringan_joins/index.html)

## Exercises

+ [intro](intro/)
+ [dplyr](dplyr/)
+ [ggplot2](ggplot2/)
\

## Useful Resources

+ [R for Data Science](https://r4ds.had.co.nz)

+ [dplyr guide](https://dplyr.tidyverse.org)

+ [ggplot2 guide](https://ggplot2.tidyverse.org)

+ [From Data to Viz](https://www.data-to-viz.com)

+ [Past Projects](https://github.com/matthewhirschey/tidybiology-final_project/tree/master/2019_fall)

+ [bespokeDS YouTube channel](https://www.youtube.com/channel/UCstAS6IpgYgZ9Cvcag_YlCQ)


<aside> The R and Tidyverse online communities are very active, helpful, and welcoming. One of the best ways to learn new things is to follow the #rstats hashtag on Twitter. </aside>


\

## Acknowledgments {.appendix}

This website was modelled on a wonderful Distill website made by [Alison Hill & Desirée De Leon](https://github.com/rstudio-education/teaching-in-production/blob/master/index.Rmd)