---
title: "Ggplot2 quiz"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(tidyverse)
data(mtcars)
knitr::opts_chunk$set(echo = FALSE)
```


## Scratchpad

Use the following empty R chunk to write the necessary code to answer the questions 

```{r scratch_pad, exercise=TRUE}


```

## Questions

### Please answer the following questions
```{r ggplot2_quiz, echo = FALSE}
quiz(
  question("Which of the following geoms would you use to make a scatter plot?",
    answer("geom_bar"),
    answer("geom_col"),
    answer("geom_point", correct = TRUE),
    answer("geom_histogram"),
    allow_retry = TRUE
  ),
  question("Which of the following symbols is used to chain together multiple lines of ggplot2 code?",
    answer("+", correct = TRUE),
    answer("<="),
    answer("->"),
    answer("->>"),
    allow_retry = TRUE
  ),
  question("Which of the following functions is used to save a plot made using ggplot2?",
    answer("save_plot"),
    answer("plot_save"),
    answer("ggsave", correct = TRUE),
    answer("geom_save"),
    allow_retry = TRUE
  ),
  question("If you had many overlapping points in a scatter plot, which of the following geoms would you use to improve your plot?",
    answer("geom_point"),       
    answer("geom_jitter", correct = TRUE),
    answer("geom_abline"),
    answer("geom_col"),
    allow_retry = TRUE
),
  question("Which of the following can you use to flip the axes of a plot?",
    answer("coord_flip", correct = TRUE),       
    answer("axis_flip"),
    answer("axes_flip"),
    answer("switch_axes"),
    allow_retry = TRUE
)
)
```

