---
title: "Tidybiology"
subtitle: "⚔<br/>Intro to Data Science Using R"
author: "Matthew Hirschey & Akshay Bareja"
institute: "Duke University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include = FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.width = 6, fig.height = 4) 
library(tidyverse)
library(kableExtra)
library(xaringanExtra)
library(janitor)
library(xaringanthemer)

happy <- read_csv("https://raw.githubusercontent.com/BAREJAA/website_for_john/master/datasets/happy_small.csv")
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#00539B",
  header_font_google = google_font("Adobe Caslon"),
  text_font_google   = google_font("Adobe Caslon", "300", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```

```{r xaringanExtra-freezeframe, echo = FALSE, message = FALSE}
options(htmltools.dir.version = FALSE)
xaringanExtra::use_freezeframe()
```

```{r xaringanExtra-clipboard, echo=FALSE}
xaringanExtra::use_clipboard()
```

```{r xaringan-panelset, echo=FALSE}
xaringanExtra::use_panelset()
```

---
class: center, middle

# Multiple if/else statements

---
# The `happy` data frame

.center[
```{r echo = FALSE}
happy %>% 
  kbl %>% 
  kable_styling()
```
]
---
# `if_else` recap

.center[
```{r echo = FALSE}
happy_if <- happy %>% 
              mutate(in_europe = if_else(country_name == "Spain", TRUE, FALSE))

happy_if %>% 
  kbl %>% 
  kable_styling()
```
]
---
# `if_else` recap

.panelset[
```{r panelset = TRUE}
happy %>% 
  mutate(in_europe = if_else(country_name == "Spain", TRUE, FALSE))
```
]
---
# More complex situations

.center[
```{r echo = FALSE}
happy %>% 
  mutate(happy_level = case_when(
    ladder_score < 4.3 ~ "unhappy",
    ladder_score >= 4.3 & ladder_score <= 6 ~ "neutral",
    TRUE ~ "happy"
  ))
```
]
---
# Multiple `if_else()`s

.panelset[
```{r panelset = TRUE}
happy %>% 
  mutate(happy_level = if_else(ladder_score < 4.3, "unhappy",
                               if_else(ladder_score >= 4.3 & ladder_score <= 6, "neutral", "happy")))
```
]
--
ugly! 
---
# `case_when()`  

.panelset[
```{r panelset = TRUE}
happy %>% 
  mutate(happy_level = case_when(
    ladder_score < 4.3 ~ "unhappy",
    ladder_score >= 4.3 & ladder_score <= 6 ~ "neutral",
    TRUE ~ "happy"
  ))
```
]
---